### ISSUE TITLE
Splunk has failed to locate the template for uri 'BetterWebhooks:/templates/credentials.html'

### ISSUE THREAD

**Issue by JykkeDaMan** [HurricaneLabs/BetterWebhooks#2]
I get this after installing the app and /debug/refresh. 
Do I need to do a full SH restart?

`2024-10-09 10:34:34,081 ERROR	[67063209f17fcdf86c15d0] __init__:353 - Unable to obtain template "BetterWebhooks:/templates/credentials.html": 
Traceback (most recent call last):
  File "/opt/splunk/lib/python3.7/site-packages/splunk/appserver/mrsparkle/controllers/__init__.py", line 348, in render_template
    templateInstance = mako_lookup.get_template(template_name)
  File "/opt/splunk/lib/python3.7/site-packages/splunk/appserver/mrsparkle/controllers/__init__.py", line 228, in get_template
    raise_top_level_lookup_exception(uri)
  File "/opt/splunk/lib/python3.7/site-packages/splunk/appserver/mrsparkle/controllers/__init__.py", line 166, in raise_top_level_lookup_exception
    raise exceptions.TopLevelLookupException(_("Splunk has failed to locate the template for uri '%s'." % uri))
TopLevelLookupException: Splunk has failed to locate the template for uri 'BetterWebhooks:/templates/credentials.html'.`

**Comment by JykkeDaMan** [comment]
Yep, works better after SH restart.

**Comment by cschmidt0121** [comment]
Sorry, yeah I've encountered this myself with multiple apps that use Splunk UI toolkit and I'm not sure if there's anything I can do to avoid requiring a restart. Thanks for the report anyway.
